// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijcZG9RBN2CiVmMYxdA7DkAXkW2vCl9A',
    appId: '1:982527880215:web:7795f3bd431dba003f8052',
    messagingSenderId: '982527880215',
    projectId: 'login-c0d76',
    authDomain: 'login-c0d76.firebaseapp.com',
    storageBucket: 'login-c0d76.appspot.com',
    measurementId: 'G-98XJBQ3YR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWjyf9fjL-HZRDINvJd5uea8E0r-NjcM',
    appId: '1:982527880215:android:2dd2a1af1c2382933f8052',
    messagingSenderId: '982527880215',
    projectId: 'login-c0d76',
    storageBucket: 'login-c0d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7hnbFae4Bti8xFLvwEwrgSQ9PPUUlTE',
    appId: '1:982527880215:ios:f3add3d877def4233f8052',
    messagingSenderId: '982527880215',
    projectId: 'login-c0d76',
    storageBucket: 'login-c0d76.appspot.com',
    iosClientId: '982527880215-8s38d4qhco9hfirbb4qj40v8979munh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7hnbFae4Bti8xFLvwEwrgSQ9PPUUlTE',
    appId: '1:982527880215:ios:f3add3d877def4233f8052',
    messagingSenderId: '982527880215',
    projectId: 'login-c0d76',
    storageBucket: 'login-c0d76.appspot.com',
    iosClientId: '982527880215-8s38d4qhco9hfirbb4qj40v8979munh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
